name: caoscruisermobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: MonsterRacing
      fonts:
        - asset: fonts/MonsterRacing/MonsterRacing.ttf
    - family: Horizon
      fonts:
        - asset: fonts/Horizon/horizon.ttf
    - family: ABeeZee
      fonts:
        - asset: fonts/ABeeZee/ABeeZee-Regular.ttf
        - asset: fonts/AbeeZee/ABeeZee-Italic.ttf
          style: italic
  uses-material-design: true
  assets:
    - img/
    - img/carros/1/
    - img/carros/2/
    - img/carros/3/
    - img/carros/4/
    - img/carros/5/
    - img/carros/6/
    - img/cenarios/1/
    - img/cenarios/2/
    - img/cenarios/3/
    - img/cenarios/4/
    - img/cenarios/5/
    - img/devs/
    - img/arte/level_design/
    - img/arte/hud/
    - img/jogo/
    - img/enduro/
    - video/